; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PIMMS"
#define MyAppVersion "1.2"
#define MyAppPublisher "Gregory Kudzin"
#define MyAppExeName "PIMMS.exe"

[Setup]
AppId={{9553FEF2-D9CA-435F-A816-EB99154F214E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
OutputDir=F:\PFAS-IMplementor-for-Mass-Spectrometry--PIMMS-\dist
OutputBaseFilename=PIMMS_v1.2_Setup
SetupIconFile=F:\PFAS-IMplementor-for-Mass-Spectrometry--PIMMS-\PIMMS v1.2\Icon\PIMMS_icon.ico
SolidCompression=yes
WizardStyle=modern

; --- Add license page ---
LicenseFile=F:\PFAS-IMplementor-for-Mass-Spectrometry--PIMMS-\license.txt

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Install your application and guide into Program Files.
Source: "F:\PFAS-IMplementor-for-Mass-Spectrometry--PIMMS-\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\PFAS-IMplementor-for-Mass-Spectrometry--PIMMS-\PIMMS Guide.pdf"; DestDir: "{userdocs}\PIMMS"; Flags: ignoreversion

; --- Install supporting files into Documents ---
Source: "F:\PFAS-IMplementor-for-Mass-Spectrometry--PIMMS-\PIMMS v1.2\Import libraries\*"; DestDir: "{userdocs}\PIMMS\Import libraries"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\PFAS-IMplementor-for-Mass-Spectrometry--PIMMS-\PIMMS v1.2\CEF_reading\*"; DestDir: "{userdocs}\PIMMS\CEF_data\Training CEF Data"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\PFAS-IMplementor-for-Mass-Spectrometry--PIMMS-\PIMMS v1.2\Raw data\NIST_SRM_Profiler_raw_data.csv"; DestDir: "{userdocs}\PIMMS\Raw data"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autoprograms}\PIMMS Guide"; Filename: "{app}\PIMMS_Guide.pdf"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
